// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "Pistol1":return img`
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
..............................................................................
.....................cb.......................................................
.....................fc.......................................................
...................ffffcf.....................................................
.................ffffffcccf...................................................
................ffccfffcbccf..................................................
................fccccccccccc..................................................
...............ffffffffffcccf.................................................
...............ffffffffffffcf.................................................
...............fffffffccfffcf.................................................
..............ffffffffccccfccf................................................
.............fffffcffccccccfcff...............................................
.............ffffccfcccccbecfcf...............................................
............fffffccfcccccbccfcff..............................................
............fffffcfcbfccdbccffcf..............................................
...........ffffffcffffcffccccfcff.............................................
...........ffffffffffffffccccffcf.............................................
..........ffffcfccffffffffcccffcff............................................
..........fffccfccfffcccccd1cfcfcf............................................
..........fffccfcffffcccbbbdcfccfc............................................
..........ffcccfffffffcccbbbcfcbdccc..........................................
.........ccdfcccfffffcccbbdbbcccccccc.........................................
........efcffccffffffffffcbdbcffcfffc.........................................
........cffffcffffffcccccdcdbcfcbcff..........................................
........ffffffffffffffccccfbbccfccff..........................................
........fffffffffffffffffcfbbcfccfccf.........................................
........fffffffffffffffffcfbccfcfffff.........................................
.........ffcfffffffffffffcfcccfcfff...........................................
.........ffcffffffffffffffccccccffc...........................................
.........ffcffffffffffffffcccbfcfcf...........................................
.........ffcfcffffffffccccccbdffffce..........................................
.........ffffcfffffffffffcccbdfcccffe.........................................
........fffffcffffffffffffcccbfcffcceee.......................................
........ffffffcffffffffffcccccfccbcfeeee......................................
.......cfffffffcfffffffcceccccfccffceeeee.....................................
.......cffffffffffccccccccccffcfcffce4eeee....................................
.......cfffffffffffffffffffffcccffcee44eeee...................................
.......cfffffffffffffffffffccccfffeee4eeeeee..................................
...ccceeeccfffffffffffffcffbccfffcee44eeeeeeee................................
..ceeeeeeeecfffffffffccfbcfbccffcee444eeeeeeeee...............................
.ceeeeeeeeeeeeffffffffcfccfcffcee4444eeeeeeeeeee..............................
ceeeeee444444eeccffffffffccccee444444eeeeeeeeeee..............................
ceeeee444443dd4eeccffffccceee444444eeeeeeeeeeeee..............................
ceeeeee4443dd333444eeeeee4444444444eeeeeeeeeeeee..............................
cecceeee44dd33444444eeeeeeee4444eeeeeee4eeeeeeec..............................
eefcceee44d34444444444eeeeeee4eeeeeee44eeeeeeeecc.............................
ccffeeeee43444444444444eeeeeeeeeee4444eeeeeeeeecee............................
ccffeeeee444444444444ee4eeeeeeeee444eeeeeeeeeeeceee...........................
cfffceeeee444444ee44444ee4444eeeee44eeeeeeeeeeeccee...........................
cfffceeeee4444ee444444444eeee4eeeeeeeeeeeeeeeecfcee...........................
fccfcceeee4444ee444434444eeeeeeeeeeeeeeeeeeeeecffce...........................
.fffcceeeee44eeee444444eeeeeeeeeeeeeeeeeeeeeecfffce...........................
...ffcceeeee4eeee444eeeee444eeeeeeeeeeeeeeeeeefffce...........................
...ffccceeeeeeeeeeeee4444eeeeeeeeeeeeeeeeeeeeecfffc...........................
...fffcceeeeeeeeeeeee44eeeee44444eeeeeeeeeeeeecfff............................
....fffcceeeeeecceee4eee4e444444444eeeeeeeeeeeccff............................
....ffffcceeeeecceeeeeee4444eeeeeeeeeeeeeeee4ecccf............................
.....fffccceeeecceeeee444eeee444444444eeeeee4ecccf............................
.....ffffccceeecceeeee4eee44444eeeee4444eeeeeeecc.............................
......ffffcccccceecceeee444eeeeeeeeeee4444eeeeecc.............................
......ffffffcccecfceeeeeeeeeeeeeeeeeeeeee44eeeecc.............................
.....ffffffffcccfceeeeeeeeeeee444443344eeeeeeeeec.............................
.....ffffffffccfceeeeeeeeeeeeeeeeee443344444eeeec.............................
.....ffffffffffceeecceeeeeeeeeee4443344eeeeeeeeeccf...........................
.....ffffffffffceefceeeeeecee4444eeeeeeeeeeeeeeeeeeee.........................
......fffffffffcccceeeeeece44eeeeeeeee443334444eeeeeccc.......................
.......fffffffcccfceeeeeee4eeeeceee444344eeeeeeeeeeccffc......................
.........ffffffffcee4eee44eecceee43344eeeeeeeecccccccfffc.....................
.........ffffffffce44ee44eecee44444eecceeeeeeeeeeeeecffff.....................
.........ffffffffcee444eecee4444eeccceeeee44eee444eeeccff.....................
.........ffffffffcee4eeccee444eeecceeeeee4444ee444eee4efc.....................
.........ffffffffceeeeccee44eeefcceeeeeee4444ee444ee44eecc....................
..........fffffffceeeecee4eeeefcceeee4ee44e44ee4eeee4eeeeccc..................
.............ffffceeecce4eeeeffceeee44ee44444ee4eeee444eeeeee.................
..............fffccccce4eeeeffcceeeee4ee44444e44ee4e4e444eeeeec...............
..............ffffcfcceeeeefffceeeeeeeeee444e444ee444444e4eeeece..............
..............fffffffceeeccfffceeeeeeeeee444e444e434444e444eeeeecc............
...............ffffffeeeecffffceeeeeeeeee4444e44e4d444e44444eeeeeeee..........
................fffffceeecfffffceeeeeeeeee444ee3444444e44e44eeeeeeeeec........
..................fffccccffffffceeeeeeeeeee34eed444eeee4e434444eeeeeeee.......
....................fccccfffffffceeeeceeeee44ee3444e4ee44444d4ee4eeeeeeeee....
.....................fcccfffcffffceeeccceee44ee3444eee4444dd44444444eeeeeecc..
.....................ffcccffccfffcceeccccee4eee44eeee4444dd3434d43e4444eeeceee
`;
            case "image1":
            case "Bullet":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 4 4 . . . . . . . 
. . . . . . 4 5 5 4 . . . . . . 
. . . . . . 2 5 5 2 . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
